# Generated by Django 5.2.7 on 2025-11-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_rename_imagem_produto_url_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='url_foto',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
